const PDFDocument = require("pdfkit");

function generatePDF(data) {
  return new Promise((resolve) => {
    const doc = new PDFDocument({ margin: 50 });
    const buffers = [];

    doc.on("data", buffers.push.bind(buffers));
    doc.on("end", () => resolve(Buffer.concat(buffers)));

    // Logo
    doc.image("public/logo.png", { width: 80 }).moveDown(1);

    // Title
    doc
      .font("Helvetica-Bold")
      .fontSize(20)
      .fillColor("#007bff")
      .text("RemoteFlow Request Summary", { align: "center" })
      .moveDown(0.5);

    // Divider
    doc
      .moveTo(50, doc.y)
      .lineTo(550, doc.y)
      .strokeColor("#007bff")
      .lineWidth(1)
      .stroke()
      .moveDown(1);

    // Section: Contact Info
    doc
      .font("Helvetica-Bold")
      .fontSize(14)
      .fillColor("#333")
      .text("Contact Information")
      .moveDown(0.5);

    doc
      .font("Helvetica")
      .fontSize(12)
      .fillColor("black")
      .text(`👤 Name: ${data.name || "—"}`)
      .text(`📧 Email: ${data.email || "—"}`)
      .text(`🏢 Company: ${data.company || "—"}`)
      .moveDown(1);

    // Section: Service Details
    doc
      .font("Helvetica-Bold")
      .fontSize(14)
      .fillColor("#333")
      .text("Service Details")
      .moveDown(0.5);

    doc
      .font("Helvetica")
      .fontSize(12)
      .text(`🛠️ Service of Interest: ${data.service || "—"}`)
      .moveDown(1);

    // Section: Message
    doc
      .font("Helvetica-Bold")
      .fontSize(14)
      .text("Client Message")
      .moveDown(0.5);

    doc
      .font("Helvetica")
      .fontSize(12)
      .text(data.message || "—", {
        align: "left",
        lineGap: 4
      });

    // Footer
    doc
      .moveDown(2)
      .fontSize(10)
      .fillColor("#888")
      .text("Generated by RemoteFlow • www.remoteflow.io", { align: "center" });

    doc.end();
  });
}

module.exports = { generatePDF };
